server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    location /console/ {
        try_files $uri $uri/ /console/index.html;
    }

    location = /console/config.json {
        add_header Cache-Control "no-store";
    }
}
